
# Site settings
# These are used to personalize your new site.
title: C. Kyle Flynn 
repository: "https://github.com/ckyleflynndev"
github_username:  username # ckyleflynndev
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  <br />
  Bachelor from Charleston Southern University in Computer and Information Science (Class of 2020)
  <br /><br />
repository: "https://github.com/ckyleflynndev"
github_username:  username # ckyleflynndev
repository: "https://github.com/ckyleflynn"
github_username:  username # ckyleflynn

# Build setting
theme: jekyll-theme-minimal

